export const todosConstants = {
    ADD_ITEM: 'ADD_ITEM',
    CHANGE_TEXT: 'CHANGE_TEXT',
    SET_TODO_STATE: 'SET_TODO_STATE',
    SET_IN_PROCESS_STATE: 'SET_IN_PROCESS_STATE',
    SET_DONE_STATE: 'SET_DONE_STATE',
    REMOVE_ITEM: 'REMOVE_ITEM',
    TOGGLE_ITEM_MENU: 'TOGGLE_ITEM_MENU',
    DISABLE_ITEM_INPUT: 'DISABLE_ITEM_INPUT',
    SHOW_ITEM_INPUT: 'SHOW_ITEM_INPUT',
    FALSE_ITEM_MENU: 'FALSE_ITEM_MENU',
}
  